[package]
name = "elf-analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1" # For parsing binary data
byteorder = "1.4" # For handling endianess
clap = {version= "4.5.26", features=["derive"]} # For CLI argument parsing
clap_derive-v3 = "3.0.0-beta.1"